name = "RequestProject"
defaultTargets = ["RequestProject"]

[[require]]
name = "mathlib"
path = "/mnt/data1/lean/mathlib"

[[lean_lib]]
name = "RequestProject"
globs = ["RequestProject.+"]

[[lean_exe]]
name = "emitwasm"
root = "EmitWasm"
