// Embed the Lean-extracted kernel into the browser bundle.
//
//   lake exe emitwasm dist && node scripts/embed-kernel.mjs
//
// Writes `web/kant-kernel-embedded.mjs`, a base64 copy of
// `dist/kant_kernel.wasm` (799 bytes -> ~1.1 kB of source). The loader in
// `web/kant-wasm.mjs` uses it whenever the binary cannot be fetched: a page
// opened from `file://`, a static host that ships only `web/`, or an offline
// browser with no cached copy. Without it those deployments silently fall back
// to the JavaScript core.
//
// The embedded copy is pinned by `web/wasm-test.mjs`, which fails if it drifts
// from `dist/kant_kernel.wasm`.

import { readFile, writeFile } from "node:fs/promises";

const root = new URL("../", import.meta.url);
const wasm = new Uint8Array(await readFile(new URL("dist/kant_kernel.wasm", root)));
const out = new URL("web/kant-kernel-embedded.mjs", root);

const b64 = Buffer.from(wasm).toString("base64");
const wrapped = (b64.match(/.{1,76}/g) ?? []).map((l) => "  \"" + l + "\"").join(" +\n");

const source = `// GENERATED by scripts/embed-kernel.mjs — do not edit.
//
// A base64 copy of dist/kant_kernel.wasm (${wasm.length} bytes), emitted by
// \`lake exe emitwasm\` from the verified encoder in RequestProject/Wasm/Encode.lean.
// web/kant-wasm.mjs falls back to this when the binary cannot be fetched, so the
// proved kernel is available from file://, from a host that ships only web/, and
// offline.

/** The kernel binary, base64-encoded. */
export const KERNEL_BASE64 =
${wrapped};

/** Byte length of the embedded kernel. */
export const KERNEL_LENGTH = ${wasm.length};

/** The embedded kernel as bytes. */
export function kernelBytes() {
  if (typeof atob === "function") {
    const bin = atob(KERNEL_BASE64);
    const out = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i += 1) out[i] = bin.charCodeAt(i);
    return out;
  }
  return new Uint8Array(Buffer.from(KERNEL_BASE64, "base64"));
}
`;

await writeFile(out, source);
console.log(`wrote ${out.pathname} (${wasm.length} bytes embedded as ${b64.length} base64 chars)`);
