[source.crates-io]
replace-with = "nora"

[source.nora]
registry = "sparse+https://solana.solfunmeme.com/nora/cargo/index/"

[registries.nora]
index = "sparse+https://solana.solfunmeme.com/nora/cargo/index/"
