// Regenerate the tracked kernel artifacts from `lake exe emitwasm`.
//
//   lake exe emitwasm dist      # writes dist/kant_kernel.wasm + dist/kernel-vectors.json
//   node scripts/embed-kernel.mjs
//   node scripts/embed-kernel.mjs --check    # verify instead of write; exit 1 on drift
//
// `dist/` is gitignored (`.gitignore`: `dist/`), so a fresh checkout has no
// kernel binary and `web/wasm-test.mjs` died on ENOENT reading it. This script
// is what makes the artifacts *tracked* rather than build output: it copies the
// emitted binary and its golden vectors into `web/`, where they are the same
// bytes the page fetches, and regenerates the base64 fallback copies.
//
// Everything it writes is derived from `dist/`, and it refuses to write a module
// the engine rejects. `--check` re-derives each file in memory and compares, so
// it can guard a tree that has drifted from the Lean output.

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = (...p) => join(root, ...p);

const check = process.argv.includes("--check");

/** Where `lake exe emitwasm dist` puts its output. */
const INPUTS = {
  wasm: src("dist", "kant_kernel.wasm"),
  vectors: src("dist", "kernel-vectors.json"),
};

/** The tracked artifacts, and who reads them. */
const OUTPUTS = {
  [src("web", "kant_kernel.wasm")]:
    "the binary `web/kant-wasm.mjs` fetches first (KERNEL_URLS[0])",
  [src("web", "kernel-vectors.json")]:
    "the 59 golden vectors `web/wasm-test.mjs` checks the binary against",
  [src("web", "kant-kernel-embedded.mjs")]:
    "the base64 fallback web/kant-wasm.mjs uses when the fetch fails",
  [src("scripts", "kant-kernel-embedded.mjs")]:
    "the same fallback, for the scripts/ copy of the loader",
};

/** base64 wrapped the way the generated module has always wrapped it. */
function wrap(b64, width = 76) {
  const lines = [];
  for (let i = 0; i < b64.length; i += width) lines.push(b64.slice(i, i + width));
  return lines.map((l, i) => `  "${l}"${i < lines.length - 1 ? " +" : ";"}`).join("\n");
}

function embeddedModule(bytes) {
  return `// GENERATED by scripts/embed-kernel.mjs — do not edit.
//
// A base64 copy of dist/kant_kernel.wasm (${bytes.length} bytes), emitted by
// \`lake exe emitwasm\` from the verified encoder in RequestProject/Wasm/Encode.lean.
// web/kant-wasm.mjs falls back to this when the binary cannot be fetched, so the
// proved kernel is available from file://, from a host that ships only web/, and
// offline.

/** The kernel binary, base64-encoded. */
export const KERNEL_BASE64 =
${wrap(Buffer.from(bytes).toString("base64"))}

/** Byte length of the embedded kernel. */
export const KERNEL_LENGTH = ${bytes.length};

/** The embedded kernel as bytes. */
export function kernelBytes() {
  if (typeof atob === "function") {
    const bin = atob(KERNEL_BASE64);
    const out = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i += 1) out[i] = bin.charCodeAt(i);
    return out;
  }
  return new Uint8Array(Buffer.from(KERNEL_BASE64, "base64"));
}
`;
}

async function read(paths, what) {
  try {
    return await readFile(paths);
  } catch (e) {
    console.error(`cannot read ${what}: ${paths}\n  ${e.message}`);
    console.error(
      "\nThese are build outputs of the Lean toolchain, not tracked files.\n" +
        "Run `lake exe emitwasm dist` first (from the checkout carrying\n" +
        "RequestProject/Wasm/Encode.lean, branch feature/lean).",
    );
    process.exit(2);
  }
}

const wasm = new Uint8Array(await read(INPUTS.wasm, "the kernel binary"));
const vectors = await read(INPUTS.vectors, "the golden vectors");

// Refuse to propagate something the engine would reject: a truncated or
// half-written binary is worse than a loud failure here.
if (!WebAssembly.validate(wasm)) {
  console.error(`dist/kant_kernel.wasm (${wasm.length} bytes) fails WebAssembly.validate`);
  process.exit(1);
}
let parsed;
try {
  parsed = JSON.parse(vectors.toString("utf8"));
} catch (e) {
  console.error(`dist/kernel-vectors.json is not valid JSON: ${e.message}`);
  process.exit(1);
}
if (!Array.isArray(parsed.vectors) || parsed.vectors.length === 0) {
  console.error("dist/kernel-vectors.json has no `vectors` array");
  process.exit(1);
}

const derived = new Map([
  [src("web", "kant_kernel.wasm"), Buffer.from(wasm)],
  // Byte-identical to the emitted file on purpose: these are Lean-computed
  // values, and any hand-edit would make them no longer Lean's.
  [src("web", "kernel-vectors.json"), vectors],
  [src("web", "kant-kernel-embedded.mjs"), Buffer.from(embeddedModule(wasm), "utf8")],
  [src("scripts", "kant-kernel-embedded.mjs"), Buffer.from(embeddedModule(wasm), "utf8")],
]);

let drift = 0;
for (const [path, want] of derived) {
  let have = null;
  try {
    have = await readFile(path);
  } catch {
    /* absent counts as drift */
  }
  const same = have !== null && have.equals(want);
  if (same) {
    console.log(`  ok    ${path.slice(root.length + 1)}`);
    continue;
  }
  drift += 1;
  const what = OUTPUTS[path];
  if (check) {
    console.log(`  DRIFT ${path.slice(root.length + 1)} — ${have ? "differs from" : "missing,"} ${what}`);
  } else {
    await writeFile(path, want);
    console.log(`  wrote ${path.slice(root.length + 1)} — ${what}`);
  }
}

const n = `${wasm.length} byte module, ${parsed.vectors.length} golden vectors`;
if (check) {
  if (drift) {
    console.error(`\n${drift} artifact(s) do not match dist/ — rerun scripts/embed-kernel.mjs`);
    process.exit(1);
  }
  console.log(`\nall tracked artifacts match dist/ (${n})`);
} else {
  console.log(`\n${drift === 0 ? "already up to date" : `${drift} written`} (${n})`);
}