// Loader for the Lean-extracted WebAssembly kernel.
//
// `dist/kant_kernel.wasm` is produced by `lake exe emitwasm dist`, whose
// encoder lives in `RequestProject/Wasm/Encode.lean`. Every exported function
// is an `i64 -> ... -> i64` and is proved in `RequestProject/Wasm/KernelSpec.lean`
// to compute the corresponding `Kant.*` definition.
//
//   import { loadKernel } from "./kant-wasm.mjs";
//   const k = await loadKernel();
//   k.mergeCids(a, b);        // BigInt in, BigInt out (unsigned)
//   k.source;                 // where the bytes came from
//
// Delivery. The binary lives outside `web/`, so a deployment that serves only
// `web/` as its document root (which is the usual one: `relay.mjs --static web`,
// an object store, a pinned directory, a USB stick) has no `/dist/` to fetch.
// Earlier versions fetched a single URL, never checked the HTTP status, and
// handed the 404 error page straight to `WebAssembly.validate`, which reported
// the misleading "kant_kernel.wasm failed validation". This loader
//
//   * tries several candidate locations, in order;
//   * rejects a response that is not OK, is empty, or does not begin with the
//     wasm magic number "\0asm", and says which of those it was;
//   * falls back to `kant-kernel-embedded.mjs`, a base64 copy of the very same
//     bytes generated by `scripts/embed-kernel.mjs`, so the proved kernel is
//     still used from `file://` and offline;
//   * only then gives up, with every attempt listed in the error message.

import { kernelBytes as embeddedKernelBytes, KERNEL_LENGTH } from "./kant-kernel-embedded.mjs";

/**
 * Locations tried, in order, before the embedded copy.
 *
 * The sibling path comes first because it is the only one that exists on every
 * deployment: web/ is the static root for the systemd relay and the worker's
 * assets directory. The dist/ paths only exist in a repository checkout, so
 * probing them first meant every deployed page load began with a guaranteed
 * 404 before falling through to a path that was right there. The remaining
 * paths are still tried, so a checkout that serves from dist/ still works.
 */
export const KERNEL_URLS = [
  new URL("./kant_kernel.wasm", import.meta.url),        // web/ shipped as the root
  new URL("./dist/kant_kernel.wasm", import.meta.url),   // dist/ copied under web/
  new URL("../dist/kant_kernel.wasm", import.meta.url),  // repository checkout
  // The two dist/ entries collapse to the same href whenever the module is
  // served from the origin root (every deployed case), so the list used to
  // fetch one 404 twice. Deduped by href, order preserved.
].filter((url, i, all) => all.findIndex((u) => u.href === url.href) === i);

/** Names exported by the module, in the order the code section holds them. */
export const KERNEL_EXPORTS = [
  "hex_digit", "cid_prefix", "cid_type", "cid_payload", "mk_cid", "merge_cids",
  "credits_for", "capacity_bytes", "social_chunks", "fits_social", "lsb_embed",
  "lsb_extract", "hex_hi", "hex_lo", "fnv_offset", "fnv1a_step", "u64_byte",
  "cantor_pair", "rotate71", "reflect59", "dual47",
];

const u64 = (x) => BigInt.asUintN(64, BigInt(x));

/** The four bytes every WebAssembly binary starts with. */
const MAGIC = [0x00, 0x61, 0x73, 0x6d];

const hasMagic = (bytes) =>
  bytes.length >= 8 && MAGIC.every((b, i) => bytes[i] === b);

/** A short, honest description of why some bytes are not a wasm module. */
function describeBytes(bytes) {
  if (bytes.length === 0) return "empty response";
  if (!hasMagic(bytes)) {
    const head = Array.from(bytes.slice(0, 16), (b) =>
      b >= 0x20 && b < 0x7f ? String.fromCharCode(b) : ".").join("");
    return `not a wasm module (${bytes.length} bytes starting "${head}")`;
  }
  return "wasm magic present but the engine rejected the module";
}

/** Fetch one candidate; throws with a precise reason on any failure. */
async function fetchWasm(url) {
  const str = String(url);
  if (typeof fetch === "function" && !str.startsWith("file:")) {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const bytes = new Uint8Array(await res.arrayBuffer());
    if (!hasMagic(bytes)) throw new Error(describeBytes(bytes));
    return bytes;
  }
  const { readFile } = await import("node:fs/promises");
  const bytes = new Uint8Array(await readFile(url));
  if (!hasMagic(bytes)) throw new Error(describeBytes(bytes));
  return bytes;
}

/**
 * The kernel bytes, and where they came from.
 * Tries every URL in `urls`, then the embedded copy.
 */
export async function kernelSource(urls = KERNEL_URLS) {
  const tried = [];
  for (const url of urls) {
    try {
      const bytes = await fetchWasm(url);
      if (!WebAssembly.validate(bytes)) throw new Error(describeBytes(bytes));
      return { bytes, source: String(url) };
    } catch (e) {
      tried.push(`${url}: ${e.message}`);
    }
  }
  try {
    const bytes = embeddedKernelBytes();
    if (!WebAssembly.validate(bytes)) throw new Error(describeBytes(bytes));
    return { bytes, source: "embedded (kant-kernel-embedded.mjs)" };
  } catch (e) {
    tried.push(`embedded copy: ${e.message}`);
  }
  throw new Error(`no usable kant_kernel.wasm — tried ${tried.join("; ")}`);
}

/**
 * Instantiate the kernel. Returns the raw exports plus camel-cased wrappers
 * that take and return unsigned `BigInt`s, and `source`, a note of where the
 * bytes were obtained.
 *
 * `url` may be a single URL (only that location is tried, then the embedded
 * copy) or an array of candidates.
 */
export async function loadKernel(url) {
  const urls = url === undefined ? KERNEL_URLS : (Array.isArray(url) ? url : [url]);
  const { bytes, source } = await kernelSource(urls);
  const { instance } = await WebAssembly.instantiate(bytes, {});
  const raw = instance.exports;
  for (const name of KERNEL_EXPORTS) {
    if (typeof raw[name] !== "function") throw new Error(`kernel is missing export ${name}`);
  }
  const call = (name) => (...args) => u64(raw[name](...args.map((a) => u64(a))));
  const kernel = {
    raw,
    bytes,
    source,
    /** True when the bytes came from the copy bundled with the page. */
    embedded: source.startsWith("embedded"),
    hexDigit: call("hex_digit"),
    cidPrefix: call("cid_prefix"),
    cidType: call("cid_type"),
    cidPayload: call("cid_payload"),
    mkCid: call("mk_cid"),
    mergeCids: call("merge_cids"),
    creditsFor: call("credits_for"),
    capacityBytes: call("capacity_bytes"),
    socialChunks: call("social_chunks"),
    fitsSocial: (n) => call("fits_social")(n) === 1n,
    lsbEmbed: call("lsb_embed"),
    lsbExtract: call("lsb_extract"),
    hexHi: call("hex_hi"),
    hexLo: call("hex_lo"),
    fnvOffset: () => u64(raw.fnv_offset()),
    fnv1aStep: call("fnv1a_step"),
    u64Byte: call("u64_byte"),
    cantorPair: call("cantor_pair"),
    /** FNV-1a 64-bit hash of a byte array, one verified step at a time. */
    fnv1a: (bytes) => {
      let h = u64(raw.fnv_offset());
      for (const b of bytes) h = call("fnv1a_step")(h, BigInt(b));
      return h;
    },
    /**
     * 32-byte content digest: four salted FNV-1a rounds, big-endian expanded.
     * Mirrors `Kant.Bytes.digest`, computed only from proved kernel exports.
     */
    digest: (bytes) => {
      const out = [];
      for (let i = 0; i < 4; i++) {
        let h = call("fnv1a_step")(u64(raw.fnv_offset()), BigInt(i));
        for (const b of bytes) h = call("fnv1a_step")(h, BigInt(b));
        for (let k = 0; k < 8; k++) out.push(Number(call("u64_byte")(h, BigInt(k))));
      }
      return out;
    },
    /** Lowercase hex of a byte array, using the verified digit functions. */
    hexEncode: (bytes) =>
      Array.from(bytes, (b) =>
        String.fromCharCode(Number(call("hex_hi")(b))) +
        String.fromCharCode(Number(call("hex_lo")(b)))).join(""),
    rotate71: call("rotate71"),
    reflect59: call("reflect59"),
    dual47: call("dual47"),
  };
  /** The witness of a paste: hex of the content digest (`Kant.Bytes.witness`). */
  kernel.witness = (bytes) => kernel.hexEncode(kernel.digest(bytes));
  return kernel;
}

export { KERNEL_LENGTH };
